### ISSUE TITLE
Error when running `esy install`

### ISSUE THREAD

**Issue by jchavarri** [astrada/ppx_bs_css#1]
When running `esy install` i'm getting this error:

```
esy install v0.0.70
info No lockfile found.
[1/4] Resolving packages...
error @opam/sedlex > @opam/gen > @opam/odoc > @opam/doc-ock@*: no version found for the current OCaml version 4.2.3004.
Consider updating OCaml version constraint of your package,
run 'npm info ocaml' to see available OCaml versions.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: @opam/sedlex > @opam/gen > @opam/odoc > @opam/doc-ock-xml > @opam/doc-ock@ >= 1.2.0: no version found for the current OCaml version 4.2.3004.
Consider updating OCaml version constraint of your package,
run 'npm info ocaml' to see available OCaml versions.
    at MessageError.Error (native)
    at new MessageError (/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:223:167)
    at OpamResolver._callee2$ (/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:86523:23)
    at tryCatch (/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:107690:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:107924:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:107742:21)
    at step (/Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:102:30)
    at /Users/javi/.nvm/versions/node/v6.11.2/lib/node_modules/esy/bin/esy.js:113:13
```

Should I run `esy` in the `next` branch? Or do something specific to help esy find these packages? (i can open an issue upstream too :)

thanks!

**Comment by astrada** [comment]
> Should I run esy in the next branch?

No, I think it's an opam repo issue. `sedlex` depends on `gen`. But gen 0.5.1 (deployed in February) depends on `odoc` that doesn't work with OCaml 4.02.3. I don't know if somehow you can pin `gen` to version 0.5 from esy config.

**Comment by astrada** [comment]
I just realized that my `.gitignore` (that I copied from https://github.com/esy-ocaml/esy-ocaml-project) contained `esy.lock`. I added that file to git, so now you should be able to run `esy install`, fetching the correct version of `gen`. (Probably you should remove `node_modules` before rerunning `esy install`.)

**Comment by jchavarri** [comment]
Thanks a lot! (and sorry for the late answer 😅 ) Now it works perfectly 💯
